# Generated by Django 3.0.8 on 2020-08-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200802_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
