# Generated by Django 3.0.8 on 2020-08-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_homestay_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homestay',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
